services:
  app:
    build: ./app
    container_name: fastapi
    env_file:
      - .env
    ports:
      - 8000:8000

  nginx:
    image: nginx:1.27.4
    container_name: nginx_fastapi
    env_file:
      - .env
    ports:
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ${CERT_PATH}/fullchain.pem:/etc/nginx/ssl/fullchain.pem
      - ${CERT_PATH}/privkey.pem:/etc/nginx/ssl/privkey.pem
    depends_on:
      - app
