services:
  app:
    build: ./app
    container_name: fastapi
    env_file:
      - .env
    ports:
      - 8000:8000

  nginx:
    build: ./nginx
    container_name: nginx_fastapi
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    environment:
      - SERVER_NAME=${SERVER_NAME}
      - URL=${URL}
    volumes:
      - ${CERT_PATH}/fullchain.pem:/etc/nginx/ssl/fullchain.pem
      - ${CERT_PATH}/privkey.pem:/etc/nginx/ssl/privkey.pem
    depends_on:
      - app
